component: scf
name: ap-guangzhou_default_jds
org: '1304011407'
app: jds
stage: dev
inputs:
  name: jds
  src: ./src
  runtime: Nodejs10.15
  region: ap-guangzhou
  description: SCF created by Tencent Serverless Toolkit for VS Code
  handler: index.main_handler
  memorySize: 128
  timeout: 3
  events:
    - apigw:
        name: serverless_api
        parameters:
          protocols:
            - http
            - https
          description: The service of Serverless Framework
          environment: release
          endpoints:
            - path: /
              method: GET

# For more information: https://github.com/serverless-components/tencent-scf/blob/v2/doc/configure.md